
#########################################################
# Function StravaSync
# Glenn Newnham
# 12.06.2022
#
# Requesting and processing strava data based on the following web site:
# https://rviews.rstudio.com/2021/11/22/strava-data/
#
#
# Requires my_sig generated by Strava_Authentication.R
# https://www.strava.com/settings/api
#
#########################################################

#########################################################
# Access Activities
# get all the activity summaries: requires my_sig
# You are now authenticated and can directly access your Strava data.
#########################################################
# 1. Load all activities

read_all_activities <- function(sig) {
	activities_url <- parse_url("https://www.strava.com/api/v3/athlete/activities")

	act_vec <- vector(mode = "list")
	df_act <- tibble::tibble(init = "init")
	i <- 1L

	while (nrow(df_act) != 0) {
		r <- activities_url %>%
			modify_url(query = list(
				access_token = sig$credentials$access_token[[1]],
				page = i
			)) %>%
			GET()

		df_act <- content(r, as = "text") %>%
			fromJSON(flatten = TRUE) %>%
			as_tibble()
		if (nrow(df_act) != 0)
			act_vec[[i]] <- df_act
		i <- i + 1L
	}

	df_activities <- act_vec %>%
		bind_rows() %>%
		mutate(start_date = ymd_hms(start_date))
}


df_act_raw = read_all_activities(my_sig)
summary(df_act_raw)
names(df_act_raw)

###################################
# 2. Preprocess activities

summary(df_act_raw$athlete.id)
pre_process_act <- function(df_act_raw, athlete_id) {
	df_act <- df_act_raw %>%
		mutate(across(contains("id"), as.character),
			   `athlete.id` = athlete_id)
}
df_act = pre_process_act(df_act_raw, 1738888)
summary(df_act_raw$athlete.id)


###################################
# 3. Extract activity IDs

library(dplyr)

act_ids = pull(distinct(df_act, id))
act_ids



###################################
# Read Measurements
# requires that you have all the metadata in df_act
###################################
# 1. Read the ‘stream’ data from Strava

read_activity_stream <- function(id, sig) {
	act_url <-
		parse_url(stringr::str_glue("https://www.strava.com/api/v3/activities/{id}/streams"))
	access_token <- sig$credentials$access_token[[1]]

	r <- modify_url(act_url,
					query = list(
						access_token = access_token,
						keys = str_glue(
							"distance,time,latlng,altitude,velocity_smooth,cadence,watts,
                      temp,moving,grade_smooth"
						)
					)) %>%
		GET()

	stop_for_status(r)

	fromJSON(content(r, as = "text"), flatten = TRUE) %>%
		as_tibble() %>%
		mutate(id = id)
}


df_meas = read_activity_stream(act_ids[1], my_sig)
df_meas

#######################################
# 2. Bind the single targets into one data frame

df_meas_all = bind_rows(df_meas)

df_meas_all

#######################################
# 3. Turn the data into a wide format

meas_wide <- function(df_meas) {
	pivot_wider(df_meas, names_from = type, values_from = data)
}
df_meas_wide = meas_wide(df_meas_all)

#######################################
# 4. Preprocess and unnest the data

meas_pro <- function(df_meas_wide) {
	df_meas_wide %>%
		mutate(
			lat = map_if(
				.x = latlng,
				.p = ~ !is.null(.x),
				.f = ~ .x[, 1]
			),
			lng = map_if(
				.x = latlng,
				.p = ~ !is.null(.x),
				.f = ~ .x[, 2]
			)
		) %>%
		select(-c(latlng, original_size, resolution, series_type)) %>%
		unnest(where(is_list))
}

df_meas_pro = meas_pro(df_meas_wide)



###################################
# Create Visualisations
# requires an activity dataframe called df_meas_pro
###################################

vis_meas = function(df_meas_pro) {
	df_meas_pro %>%
		filter(!is.na(lat)) %>%
		ggplot(aes(x = lng, y = lat)) +
		geom_path() +
		facet_wrap( ~ id, scales = "free") +
		theme(
			axis.line = element_blank(),
			axis.text.x = element_blank(),
			axis.text.y = element_blank(),
			axis.ticks = element_blank(),
			axis.title.x = element_blank(),
			axis.title.y = element_blank(),
			legend.position = "bottom",
			panel.background = element_blank(),
			panel.border = element_blank(),
			panel.grid.major = element_blank(),
			panel.grid.minor = element_blank(),
			plot.background = element_blank(),
			strip.text = element_blank()
		)
}

gg_meas = vis_meas(df_meas_pro)
gg_meas

