
#########################################################
# Function StravaSync
# Glenn Newnham
# 12.06.2022
#
# Requesting and processing strava data based on the folliwng web site:
# https://rviews.rstudio.com/2021/11/22/strava-data/
#
#
# Requires my_sig generated by Strava_Authentication.R
# https://www.strava.com/settings/api
#
#########################################################

# Prerequisites: Rtools external installation, Create an OAuth Strava app, install the following packages:
# install.packages("usethis")

library(usethis)
library(tarchetypes)
library(conflicted)
library(tidyverse)
library(lubridate)
library(jsonlite)
library(targets)
library(httpuv)
library(httr)
library(pins)
library(httr)
library(fs)
library(readr)

conflict_prefer("filter", "dplyr")

# ### type "usethis::edit_r_environ()" and add thee following to 'C:/Users/new298/Documents/.Renviron'
# STRAVA_KEY = 87643
# STRAVA_SECRET = "fbf47f3fbb53b43af16e9c3abfe1d64f3519d691"

App_Name = "RSync"

define_strava_app <- function() {
	oauth_app(
		appname = App_Name,
		key = Sys.getenv("STRAVA_KEY"),
		secret = Sys.getenv("STRAVA_SECRET")
	)
}

my_app = define_strava_app()
my_app


define_strava_endpoint <- function() {
	oauth_endpoint(request = NULL,
				   authorize = "https://www.strava.com/oauth/authorize",
				   access = "https://www.strava.com/oauth/token")
}

my_endpoint = define_strava_endpoint()
my_endpoint


define_strava_sig <- function(endpoint, app) {
	oauth2.0_token(
		endpoint,
		app,
		scope = "activity:read_all,activity:read,profile:read_all",
		type = NULL,
		use_oob = FALSE,
		as_header = FALSE,
		use_basic_auth = FALSE,
		cache = FALSE
	)
}

my_sig = define_strava_sig(my_endpoint, my_app)
my_sig$credentials


#############################################
### Now get the data
#############################################


read_all_activities <- function(sig) {
	activities_url <- parse_url("https://www.strava.com/api/v3/athlete/activities")

	act_vec <- vector(mode = "list")
	df_act <- tibble::tibble(init = "init")
	i <- 1L

	while (nrow(df_act) != 0) {
		r <- activities_url %>%
			modify_url(query = list(
				access_token = sig$credentials$access_token[[1]],
				page = i
			)) %>%
			GET()

		df_act <- content(r, as = "text") %>%
			fromJSON(flatten = TRUE) %>%
			as_tibble()
		if (nrow(df_act) != 0)
			act_vec[[i]] <- df_act
		i <- i + 1L
	}

	df_activities <- act_vec %>%
		bind_rows() %>%
		mutate(start_date = ymd_hms(start_date))
}


df_act_raw = read_all_activities(my_sig)



